[dependencies]
clap = '3.0.0-beta.5'
rustfft = '6.0.1'
ndarray = {version='0.15.4', features=['rayon']}
ndarray-npy='0.8.1'
num='0.4.0'
rand='0.8.4'
rand_chacha='0.3.1'
rand_distr='0.4.2'
pinknoise={path='../pinknoise'}

[package]
edition = '2021'
name = 'observe_1f'
version = '0.1.0'

